"""empty message

Revision ID: 1f44bf2fb5ce
Revises: c6afbe822f82
Create Date: 2025-01-21 05:17:59.323559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f44bf2fb5ce'
down_revision = 'c6afbe822f82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('FIRST_NAME', sa.String(length=25), nullable=False))
        batch_op.add_column(sa.Column('LAST_NAME', sa.String(length=25), nullable=False))
        batch_op.create_unique_constraint(None, ['USER_ID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('LAST_NAME')
        batch_op.drop_column('FIRST_NAME')

    # ### end Alembic commands ###
