"""Adding the courses model

Revision ID: 4abe982280e6
Revises: 5ae133abb118
Create Date: 2024-12-14 09:24:12.380258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4abe982280e6'
down_revision = '5ae133abb118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('COURSE_ID', sa.Integer(), nullable=False),
    sa.Column('FACILITY_ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(length=50), nullable=True),
    sa.Column('HOLE_COUNT', sa.Integer(), nullable=False, server_default=18),
    sa.Column('ESTABLISHED', sa.Integer(), nullable=True),
    sa.Column('ARCHITECT', sa.String(length=100), nullable=True),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['FACILITY_ID'], ['facility.FACILITY_ID'], ),
    sa.PrimaryKeyConstraint('COURSE_ID'),
    sa.UniqueConstraint('COURSE_ID')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_check_constraint('CHECK_CRSE_ESTABLISHED_MIN', sa.sql.column('ESTABLISHED') > 1574)
        batch_op.create_check_constraint('CHECK_CRSE_HOLE_COUNT_MIN', sa.sql.column('HOLE_COUNT') > 0)
        batch_op.create_check_constraint('CHECK_CRSE_HOLE_COUNT_MAX', sa.sql.column('HOLE_COUNT') <= 18)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('course')
    # ### end Alembic commands ###
