"""Adding the facility model

Revision ID: 5ae133abb118
Revises: 
Create Date: 2024-12-14 08:27:12.508324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae133abb118'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
        sa.Column('FACILITY_ID', sa.Integer(), nullable=False),
        sa.Column('NAME', sa.String(length=100), nullable=False),
        sa.Column('HANDLE', sa.String(length=25), nullable=False),
        sa.Column('CLASSIFICATION', sa.Enum('D', 'P', 'R', 'M','S' 'O', name='FACILITY_CLASSIFICATION'), server_default='O', nullable=False),
        sa.Column('COURSE_COUNT', sa.Integer(), server_default='1', nullable=False),
        sa.Column('ESTABLISHED', sa.Integer(), nullable=True),
        sa.Column('WEBSITE', sa.String(length=100), nullable=True),
        sa.Column('ADDRESS', sa.String(length=100), nullable=True),
        sa.Column('CITY', sa.String(length=50), nullable=True),
        sa.Column('STATE', sa.String(length=3), nullable=True),
        sa.Column('COUNTRY', sa.String(length=3), nullable=True),
        sa.Column('GEO_LAT', sa.FLOAT(), nullable=True),
        sa.Column('GEO_LON', sa.FLOAT(), nullable=True),
        sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
        sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
        sa.PrimaryKeyConstraint('FACILITY_ID'),
        sa.UniqueConstraint('FACILITY_ID'),
        sa.UniqueConstraint('HANDLE')
    )

    with op.batch_alter_table('facility') as batch_op:
        batch_op.create_check_constraint('CHECK_COURSE_COUNT', sa.sql.column('COURSE_COUNT') > 0)
        batch_op.create_check_constraint('CHECK_ESTABLISHED_MIN', sa.sql.column('ESTABLISHED') > 1400)
        batch_op.create_check_constraint('CHECK_GEO_LAT_MIN', sa.sql.column('GEO_LAT') > -90)
        batch_op.create_check_constraint('CHECK_GEO_LAT_MAX', sa.sql.column('GEO_LAT') < 90)
        batch_op.create_check_constraint('CHECK_GEO_LON_MIN', sa.sql.column('GEO_LON') > -180)
        batch_op.create_check_constraint('CHECK_GEO_LON_MAX', sa.sql.column('GEO_LON') < 180)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility')
    # ### end Alembic commands ###
