"""Adding the tees model

Revision ID: 6d8f5b4c1980
Revises: 4abe982280e6
Create Date: 2024-12-14 10:50:08.184356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8f5b4c1980'
down_revision = '4abe982280e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tee',
    sa.Column('TEE_ID', sa.Integer(), nullable=False),
    sa.Column('COURSE_ID', sa.Integer(), nullable=False),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('YARDS', sa.Integer(), server_default='7200', nullable=False),
    sa.Column('METERS', sa.Integer(), server_default='6600', nullable=False),
    sa.Column('HOLE_COUNT', sa.Integer(), server_default='18', nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['COURSE_ID'], ['course.COURSE_ID'], ),
    sa.ForeignKeyConstraint(['FACILITY_ID'], ['facility.FACILITY_ID'], onupdate="CASCADE", ondelete="CASCADE"),
    sa.PrimaryKeyConstraint('TEE_ID')
    )
    with op.batch_alter_table('tee', schema=None) as batch_op:
        batch_op.create_check_constraint('CHECK_TEE_YARDS', sa.sql.column('YARDS') > 0)
        batch_op.create_check_constraint('CHECK_TEE_METERS', sa.sql.column('METERS') > 0)
        batch_op.create_check_constraint('CHECK_TEE_HOLE_COUNT_MIN', sa.sql.column('HOLE_COUNT') > 0)
        batch_op.create_check_constraint('CHECK_TEE_HOLE_COUNT_MAX', sa.sql.column('HOLE_COUNT') <= 18)       

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tee')

    # ### end Alembic commands ###
