"""Adding the ratings model

Revision ID: 8b8ac6403f3a
Revises: 6d8f5b4c1980
Create Date: 2024-12-14 11:57:24.002929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8ac6403f3a'
down_revision = '6d8f5b4c1980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating',
    sa.Column('RATING_ID', sa.Integer(), nullable=False),
    sa.Column('TEE_ID', sa.Integer(), nullable=True),
    sa.Column('NAME', sa.String(), nullable=False),
    sa.Column('HOLE_COUNT', sa.Integer(), nullable=True , server_default='18'),
    sa.Column('GENDER', sa.Enum('M', 'F', name='COURSE_RATING_GENDER'), server_default='M', nullable=False),
    sa.Column('START_HOLE', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('COURSE_RATING', sa.FLOAT(), nullable=False),
    sa.Column('SLOPE', sa.Integer(), nullable=False),
    sa.Column('PAR', sa.Integer(), nullable=False),
    sa.Column('BOGEY_RATING', sa.FLOAT(), nullable=True),
    sa.Column('EFFECTIVE_DATE', sa.DATE(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['TEE_ID'], ['tee.TEE_ID'], ),
    sa.PrimaryKeyConstraint('RATING_ID')
    )
    with op.batch_alter_table('rating', schema=None) as batch_op:
        batch_op.create_check_constraint('CHECK_RATING_START_HOLE_MIN', sa.sql.column('START_HOLE') >= 1)
        batch_op.create_check_constraint('CHECK_RATING_START_HOLE_MAX', sa.sql.column('START_HOLE') <= 18)
        batch_op.create_check_constraint('CHECK_RATING_START_HOLE_TOTAL', sa.sql.column('START_HOLE') <= sa.sql.column('HOLE_COUNT'))        
        batch_op.create_check_constraint('CHECK_RATING_SLOPE_MIN', sa.sql.column('SLOPE') >= 55)
        batch_op.create_check_constraint('CHECK_RATING_SLOPE_MAX', sa.sql.column('SLOPE') <= 155)
        batch_op.create_check_constraint('CHECK_RATING_PAR_MIN', sa.sql.column('PAR') >= 27)
        batch_op.create_check_constraint('CHECK_RATING_PAR_MAX', sa.sql.column('PAR') <= 80)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rating')

    # ### end Alembic commands ###
