"""empty message

Revision ID: c6afbe822f82
Revises: b3020030abda
Create Date: 2025-01-18 11:28:23.354912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6afbe822f82'
down_revision = 'b3020030abda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('USERNAME', sa.String(length=25), nullable=False),
    sa.Column('EMAIL', sa.String(length=50), nullable=False),
    sa.Column('GENDER', sa.Enum('M', 'F', 'N', 'P', name='USER_GENDER'), server_default='P', nullable=False),
    sa.Column('DOB', sa.DATE(), nullable=False),
    sa.Column('PLAYER_TYPE', sa.Enum('A', 'C', 'P', 'TP', name='USER_TYPE'), server_default='A', nullable=False),
    sa.Column('HOME_FACILITY', sa.Integer(), nullable=True),
    sa.Column('NATIONALITY', sa.String(length=3), nullable=True),
    sa.Column('UNITS', sa.Enum('Y', 'M', name='USER_UNITS'), server_default='Y', nullable=False),
    sa.Column('ROLE', sa.Enum('basic', 'vip', 'admin', name='USER_ROLE'), server_default='basic', nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['HOME_FACILITY'], ['facility.FACILITY_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('USER_ID'),
    sa.UniqueConstraint('EMAIL'),
    sa.UniqueConstraint('USERNAME'),
    sa.UniqueConstraint('USER_ID')
    )
    op.create_table('user_auth',
    sa.Column('AUTH_ID', sa.Integer(), nullable=False),
    sa.Column('USER_ID', sa.Integer(), nullable=False),
    sa.Column('SALT', sa.String(length=50), nullable=False),
    sa.Column('PASSWORD_HASH', sa.String(length=100), nullable=False),
    sa.Column('GUID_TOKEN', sa.String(length=50), nullable=False),
    sa.Column('GUID_EXPIRE', sa.TIMESTAMP(), nullable=False),
    sa.Column('CREATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.Column('UPDATED_AT', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['USER_ID'], ['user.USER_ID'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('AUTH_ID'),
    sa.UniqueConstraint('AUTH_ID')
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('user_auth')
    op.drop_table('user')
    # ### end Alembic commands ###
