# LONNIE POOLE GOLF COURSE SEED DATA
course_seed = {
	"FACILITY": {
		"FACILITY_ID": 88,
		"NAME": "Lonnie Poole GC at N.C. State University",
		"ADDRESS": "1509 Main Campus Dr, Raleigh, NC 27606, USA",
		"GEO_LON": -78.6772029,
		"GEO_LAT": 35.7600764,
		"COURSE_COUNT": 1,
		"CLASSIFICATION": "D",
		"CITY": "Raleigh",
		"STATE": "NC",
		"COUNTRY": "USA",
		"WEBSITE": "www.lonniepoolegolfcourse.com",
		"ESTABLISHED": 2007,
		"HANDLE": "lonniepoolegc"
	},
	"COURSE": [{
		"COURSE_ID": 101,
		"NAME": None,
		"HOLE_COUNT": 18,
    "ESTABLISHED": 2007,
    "ARCHITECT": "Arnold Palmer",
    "TEES": [{		
      "TEE_ID": 450729,
      "YARDS": 7212,
      "METERS":	6595,
      "HOLE_COUNT": 18,
      "NAME": "Competition Tees",
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 74.6,
        "SLOPE": 142,
        "PAR": 72,
        "BOGEY_RATING": 101.0
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 36.9,
        "SLOPE": 142,
        "PAR": 36,
        "BOGEY_RATING": 50.1
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "COURSE_RATING": 37.7,
        "SLOPE": 142,
        "PAR": 36,
        "BOGEY_RATING": 50.9
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 567,
        "PAR_MALE": 5,
        "SI_MALE": 11
      }, {
        "NUMBER": 2,
        "YARDS": 227,
        "PAR_MALE": 3,
        "SI_MALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 542,
        "PAR_MALE": 5,
        "SI_MALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 357,
        "PAR_MALE": 4,
        "SI_MALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 455,
        "PAR_MALE": 4,
        "SI_MALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 153,
        "PAR_MALE": 3,
        "SI_MALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 579,
        "PAR_MALE": 5,
        "SI_MALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 172,
        "PAR_MALE": 3,
        "SI_MALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 480,
        "PAR_MALE": 4,
        "SI_MALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 385,
        "PAR_MALE": 4,
        "SI_MALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 651,
        "PAR_MALE": 5,
        "SI_MALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 460,
        "PAR_MALE": 4,
        "SI_MALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 442,
        "PAR_MALE": 4,
        "SI_MALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 189,
        "PAR_MALE": 3,
        "SI_MALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 549,
        "PAR_MALE": 5,
        "SI_MALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 402,
        "PAR_MALE": 4,
        "SI_MALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 129,
        "PAR_MALE": 3,
        "SI_MALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 473,
        "PAR_MALE": 4,
        "SI_MALE": 4
      }]
    }, {				  
      "TEE_ID": 161195,
      "YARDS": 6871,
      "METERS":	6283,
      "HOLE_COUNT": 18,
      "NAME": "Black Tees",
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 72.9,
        "SLOPE": 139,
        "PAR": 72,
        "BOGEY_RATING": 98.7
        }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 36.0,
        "SLOPE": 139,
        "PAR": 36,
        "BOGEY_RATING": 48.9
        }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "COURSE_RATING": 36.9,
        "SLOPE": 139,
        "PAR": 36,
        "BOGEY_RATING": 49.8
        }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 529,
        "PAR_MALE": 5,
        "SI_MALE": 11
      }, {
        "NUMBER": 2,
        "YARDS": 213,
        "PAR_MALE": 3,
        "SI_MALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 517,
        "PAR_MALE": 5,
        "SI_MALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 357,
        "PAR_MALE": 4,
        "SI_MALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 451,
        "PAR_MALE": 4,
        "SI_MALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 150,
        "PAR_MALE": 3,
        "SI_MALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 547,
        "PAR_MALE": 5,
        "SI_MALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 161,
        "PAR_MALE": 3,
        "SI_MALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 427,
        "PAR_MALE": 4,
        "SI_MALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 380,
        "PAR_MALE": 4,
        "SI_MALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 618,
        "PAR_MALE": 5,
        "SI_MALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 412,
        "PAR_MALE": 4,
        "SI_MALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 408,
        "PAR_MALE": 4,
        "SI_MALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 186,
        "PAR_MALE": 3,
        "SI_MALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 541,
        "PAR_MALE": 5,
        "SI_MALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 397,
        "PAR_MALE": 4,
        "SI_MALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 122,
        "PAR_MALE": 3,
        "SI_MALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 455,
        "PAR_MALE": 4,
        "SI_MALE": 4
      }]
    }, {					
      "TEE_ID": 161196,
      "NAME": "Red Tees",
      "HOLE_COUNT": 18,
      "YARDS": 6388,
      "METERS":	5841,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 70.7,
        "SLOPE": 135,
        "BOGEY_RATING": 95.7,
        "PAR": 72
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 35,
        "SLOPE": 133,
        "BOGEY_RATING": 47.4,
        "PAR": 36
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "COURSE_RATING": 35.7,
        "SLOPE": 136,
        "BOGEY_RATING": 48.3,
        "PAR": 36
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "COURSE_RATING": 76.5,
        "SLOPE": 143,
        "BOGEY_RATING": 110.3,
        "PAR": 72
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "START_HOLE": 1,
        "GENDER": "F",
        "COURSE_RATING": 37.8,
        "SLOPE": 142,
        "BOGEY_RATING": 54.6,
        "PAR": 36
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "START_HOLE": 10,
        "GENDER": "F",
        "COURSE_RATING": 38.7,
        "SLOPE": 144,
        "BOGEY_RATING": 55.7,
        "PAR": 36
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 498,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11

      }, {
        "NUMBER": 2,
        "YARDS": 203,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 489,
        "PAR_MALE": 5,
        "SI_MALE": 1,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1

      }, {
        "NUMBER": 4,
        "YARDS": 334,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13

      }, {
        "NUMBER": 5,
        "YARDS": 413,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 140,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 531,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 138,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 387,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 362,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 546,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 383,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8

      }, {
        "NUMBER": 13,
        "YARDS": 377,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 159,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 499,
        "PAR_MALE": 5,
        "SI_MALE": 6,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 376,
        "PAR_MALE": 4,
        "SI_MALE": 12,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 117,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 436,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }, {					
      "TEE_ID": 450733,
      "NAME": "Wolfpack Tees",
      "HOLE_COUNT": 18,
      "YARDS": 5935,
      "METERS": 5427,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 68.8,
        "SLOPE": 126,
        "BOGEY_RATING": 92.2,
        "PAR": 72
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "COURSE_RATING": 34.0,
        "SLOPE": 123,
        "BOGEY_RATING": 45.4,
        "PAR": 72
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "COURSE_RATING": 34.8,
        "SLOPE": 129,
        "BOGEY_RATING": 46.8,
        "PAR": 72
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "COURSE_RATING": 74,
        "SLOPE": 138,
        "BOGEY_RATING": 106.5,
        "PAR": 72
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 1,
        "COURSE_RATING": 36.5,
        "SLOPE": 137,
        "BOGEY_RATING": 52.6,
        "PAR": 72
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 10,
        "COURSE_RATING": 37.5,
        "SLOPE": 139,
        "BOGEY_RATING": 53.9,
        "PAR": 72
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 490,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11

      }, {
        "NUMBER": 2,
        "YARDS": 178,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 458,
        "PAR_MALE": 5,
        "SI_MALE": 1,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1

      }, {
        "NUMBER": 4,
        "YARDS": 287,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13

      }, {
        "NUMBER": 5,
        "YARDS": 391,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 136,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 485,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 124,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 349,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 340,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 517,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 350,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8

      }, {
        "NUMBER": 13,
        "YARDS": 344,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 138,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 469,
        "PAR_MALE": 5,
        "SI_MALE": 6,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 345,
        "PAR_MALE": 4,
        "SI_MALE": 12,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 110,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 424,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }, {					
      "TEE_ID": 711179,
      "NAME": "Wolfpack/Gray Hybrid",
      "HOLE_COUNT": 18,
      "YARDS": 5605,
      "METERS": 4639,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 67,
        "SLOPE": 122,
        "BOGEY_RATING": 89.5
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 33.1,
        "SLOPE": 121,
        "BOGEY_RATING": 44.3
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 33.9,
        "SLOPE": 122,
        "BOGEY_RATING": 45.2
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 71.9,
        "SLOPE": 131,
        "BOGEY_RATING": 102.7
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 35.5,
        "SLOPE": 127,
        "BOGEY_RATING": 50.5
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 36.4,
        "SLOPE": 134,
        "BOGEY_RATING": 52.2
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 441,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11

      }, {
        "NUMBER": 2,
        "YARDS": 178,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 458,
        "PAR_MALE": 5,
        "SI_MALE": 1,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 287,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 351,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5

      }, {
        "NUMBER": 6,
        "YARDS": 136,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 438,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 113,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 349,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 340,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 472,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 350,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 336,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 120,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 469,
        "PAR_MALE": 5,
        "SI_MALE": 6,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 289,
        "PAR_MALE": 4,
        "SI_MALE": 12,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 110,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 368,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }, {					
      "TEE_ID": 450731,
      "NAME": "Gray Tees",
      "GENDER": "M",
      "HOLE_COUNT": 18,
      "YARDS": 5339,
      "METERS": 4882,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 66.1,
        "SLOPE": 116,
        "BOGEY_RATING": 87.7
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 32.8,
        "SLOPE": 116,
        "BOGEY_RATING": 43.6
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 33.3,
        "SLOPE": 116,
        "BOGEY_RATING": 44.1
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 70.5,
        "SLOPE": 127,
        "BOGEY_RATING": 100.5
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 34.8,
        "SLOPE": 122,
        "BOGEY_RATING": 49.2
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 35.7,
        "SLOPE": 132,
        "BOGEY_RATING": 51.3
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 441,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11

      }, {
        "NUMBER": 2,
        "YARDS": 163,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 443,
        "PAR_MALE": 5,
        "SI_MALE": 1,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 252,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 351,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 107,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 438,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 113,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 314,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 281,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 472,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 320,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 336,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 120,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 427,
        "PAR_MALE": 5,
        "SI_MALE": 6,			
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 289,
        "PAR_MALE": 4,
        "SI_MALE": 12,		
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 104,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 368,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }, { 					
      "TEE_ID": 483755,
      "NAME": "Gray/Green Hybrid",
      "GENDER": "M",
      "HOLE_COUNT": 18,
      "YARDS": 5073,
      "METERS": 4639,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 64.9,
        "SLOPE": 112,
        "BOGEY_RATING": 85.7
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 32.2,
        "SLOPE": 112,
        "BOGEY_RATING": 42.6
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 32.7,
        "SLOPE": 112,
        "BOGEY_RATING": 43.1
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 69.1,
        "SLOPE": 121,
        "BOGEY_RATING": 97.6
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 34.1,
        "SLOPE": 117,
        "BOGEY_RATING": 37.9
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 35.0,
        "SLOPE": 125,
        "BOGEY_RATING": 49.7
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 387,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11
      }, {
        "NUMBER": 2,
        "YARDS": 163,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 443,
        "PAR_MALE": 5,
        "SI_MALE": 1,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 252,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 271,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 107,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 438,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 113,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 314,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 281,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 467,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 289,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 304,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 120,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 427,
        "PAR_MALE": 5,
        "SI_MALE": 6,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 289,
        "PAR_MALE": 4,
        "SI_MALE": 12,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 89,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 319,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }, {		
      "TEE_ID": 161198,
      "NAME": "Green Tees",
      "GENDER": "M",
      "HOLE_COUNT": 18,
      "YARDS": 4652,
      "METERS": 4254,
      "RATINGS": [{
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 62.9,
        "SLOPE": 109,
        "BOGEY_RATING": 83
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 31.1,
        "SLOPE": 108,
        "BOGEY_RATING": 41.1
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "M",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 31.8,
        "SLOPE": 109,
        "BOGEY_RATING": 41.9
      }, {
        "NAME": "Full",
        "HOLE_COUNT": 18,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 72,
        "COURSE_RATING": 67,
        "SLOPE": 115,
        "BOGEY_RATING": 94
      }, {
        "NAME": "Front",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 1,
        "PAR": 36,
        "COURSE_RATING": 32.7,
        "SLOPE": 115,
        "BOGEY_RATING": 46.3
      }, {
        "NAME": "Back",
        "HOLE_COUNT": 9,
        "GENDER": "F",
        "START_HOLE": 10,
        "PAR": 36,
        "COURSE_RATING": 34.3,
        "SLOPE": 114,
        "BOGEY_RATING": 47.7
      }],
      "HOLES": [{
        "NUMBER": 1,
        "YARDS": 387,
        "PAR_MALE": 5,
        "SI_MALE": 11,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 11
      }, {
        "NUMBER": 2,
        "YARDS": 140,
        "PAR_MALE": 3,
        "SI_MALE": 9,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 9
      }, {
        "NUMBER": 3,
        "YARDS": 334,
        "PAR_MALE": 5,
        "SI_MALE": 1,			
        "PAR_FEMALE": 5,
        "SI_FEMALE": 1
      }, {
        "NUMBER": 4,
        "YARDS": 233,
        "PAR_MALE": 4,
        "SI_MALE": 13,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 13
      }, {
        "NUMBER": 5,
        "YARDS": 271,
        "PAR_MALE": 4,
        "SI_MALE": 5,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 5
      }, {
        "NUMBER": 6,
        "YARDS": 86,
        "PAR_MALE": 3,
        "SI_MALE": 17,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 17
      }, {
        "NUMBER": 7,
        "YARDS": 396,
        "PAR_MALE": 5,
        "SI_MALE": 7,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 7
      }, {
        "NUMBER": 8,
        "YARDS": 94,
        "PAR_MALE": 3,
        "SI_MALE": 15,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 15
      }, {
        "NUMBER": 9,
        "YARDS": 279,
        "PAR_MALE": 4,
        "SI_MALE": 3,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 3
      }, {
        "NUMBER": 10,
        "YARDS": 231,
        "PAR_MALE": 4,
        "SI_MALE": 16,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 16
      }, {
        "NUMBER": 11,
        "YARDS": 467,
        "PAR_MALE": 5,
        "SI_MALE": 2,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 2
      }, {
        "NUMBER": 12,
        "YARDS": 289,
        "PAR_MALE": 4,
        "SI_MALE": 8,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 8
      }, {
        "NUMBER": 13,
        "YARDS": 304,
        "PAR_MALE": 4,
        "SI_MALE": 10,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 10
      }, {
        "NUMBER": 14,
        "YARDS": 99,
        "PAR_MALE": 3,
        "SI_MALE": 14,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 14
      }, {
        "NUMBER": 15,
        "YARDS": 399,
        "PAR_MALE": 5,
        "SI_MALE": 6,
        "PAR_FEMALE": 5,
        "SI_FEMALE": 6
      }, {
        "NUMBER": 16,
        "YARDS": 235,
        "PAR_MALE": 4,
        "SI_MALE": 12,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 12
      }, {
        "NUMBER": 17,
        "YARDS": 89,
        "PAR_MALE": 3,
        "SI_MALE": 18,
        "PAR_FEMALE": 3,
        "SI_FEMALE": 18
      }, {
        "NUMBER": 18,
        "YARDS": 319,
        "PAR_MALE": 4,
        "SI_MALE": 4,
        "PAR_FEMALE": 4,
        "SI_FEMALE": 4
      }]
    }]
  }]
}
